#########################################################################
#
#     Dockerfile.adgs.auxip.localhost
#
#########################################################################
#
# Dockerfile for auxip @ ADGS
# 
# ALPINE
# https://pkgs.alpinelinux.org/packages
#
FROM python:3.11-alpine

ARG UID_HOST_USER
ARG GID_HOST_USER

# ================================================
RUN apk update && apk add --no-cache build-base
RUN apk --no-cache add procps
RUN apk --no-cache add curl
RUN apk --no-cache add openssl curl-dev
RUN apk --no-cache add bash
RUN apk --no-cache add jq
RUN apk --no-cache add openssh
RUN apk --no-cache add sshpass
RUN apk --no-cache add p7zip
RUN apk --no-cache add postgresql-client
RUN apk --no-cache add postgresql-dev


# change default shell from ash to bash
RUN sed -i -e "s/bin\/ash/bin\/bash/" /etc/passwd

# in case it is executed rootless to resolve the adgs_db hostname
# https://forums.docker.com/t/docker-compose-build-error-on-mac-chmod-changing-permissions-of-etc-resolv-conf-read-only-file-system/139187
# RUN chmod a+r /etc/resolv.conf

RUN addgroup -g $GID_HOST_USER -S adgs && adduser -u $UID_HOST_USER -S adgs -G adgs -s /bin/bash

# Create directory where the auxip repository is going to be attached for development
RUN mkdir /auxip
RUN mkdir /scripts
RUN mkdir /resources_path
RUN chown adgs:adgs /auxip /scripts /resources_path

USER adgs

RUN openssl req -x509 -newkey rsa:4096 -nodes -out /resources_path/certificate.pem -keyout /resources_path/key.pem -subj "/emailAddress=daniel.brosnan@elecnor.es/C=SP/ST=Madrid/L=Tres Cantos/O=Elecnor Deimos/OU=Ground Segment/CN=AUXIP"

# Add path to the scripts installed by pip in the home of the adgs user to PATH
ENV PATH="${PATH}:/home/adgs/.local/bin"

WORKDIR /auxip

CMD ["/bin/bash", "-c", "pip3 install -e '/auxip[tests]'; uvicorn auxip.main:app --ssl-certfile /resources_path/certificate.pem --ssl-keyfile /resources_path/key.pem --proxy-headers --host 0.0.0.0 --log-level debug --reload"]