#########################################################################
#
#     Dockerfile.adgs.auxip.localhost
#
#########################################################################
#
# Dockerfile for auxip @ ADGS
# 
# ALPINE
# https://pkgs.alpinelinux.org/packages
#
FROM python:3.11-alpine

ARG AUXIP_PACKAGE

# ================================================
RUN apk update && apk add --no-cache build-base
RUN apk --no-cache add procps
RUN apk --no-cache add curl
RUN apk --no-cache add openssl curl-dev
RUN apk --no-cache add bash
RUN apk --no-cache add jq
RUN apk --no-cache add openssh
RUN apk --no-cache add sshpass
RUN apk --no-cache add p7zip
RUN apk --no-cache add postgresql-client
RUN apk --no-cache add postgresql-dev


# change default shell from ash to bash
RUN sed -i -e "s/bin\/ash/bin\/bash/" /etc/passwd

# in case it is executed rootless to resolve the adgs_db hostname
# https://forums.docker.com/t/docker-compose-build-error-on-mac-chmod-changing-permissions-of-etc-resolv-conf-read-only-file-system/139187
# RUN chmod a+r /etc/resolv.conf

RUN addgroup -g 2020 -S adgs && adduser -u 2020 -S adgs -G adgs -s /bin/bash

# Copy AUXIP package
RUN mkdir /auxip_packages
COPY --from=auxip_packages_directory $AUXIP_PACKAGE /auxip_packages
RUN chown -R adgs:adgs /auxip_packages
    
# Create folders for AUXIP
RUN mkdir /scripts
RUN mkdir /resources_path

# Change ownership to the boa user
RUN chown -R adgs /scripts /resources_path

USER adgs

# Add path to the scripts installed by pip in the home of the adgs user to PATH
ENV PATH="${PATH}:/home/adgs/.local/bin"

# Install AUXIP package
RUN pip3 install /auxip_packages/*

RUN echo "while true; do echo 'Trying to start the web server...'; uvicorn --ssl-certfile /resources_path/certificate.pem --ssl-keyfile /resources_path/key.pem auxip.main:app --proxy-headers --host 0.0.0.0; if [[ $? != 0 ]]; then echo 'Failed to start the web server...'; sleep 1; else echo 'Web server started! :D'; fi; done; sleep infinity" > /scripts/start_uvicorn.sh

RUN chmod u+x /scripts/start_uvicorn.sh


CMD ["/bin/bash", "-c", "/scripts/start_uvicorn.sh"]