{
 "title": "ADGS AUXIP metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Cumulative downloaded volume from AUXIP per day",
   "type": "timeseries",
   "description": "Cumulative downloaded volume from AUXIP per day in MB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "auxip_cumulative_downloaded_volume_per_day / 10000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative downloaded volume from AUXIP by client per day",
   "type": "timeseries",
   "description": "Cumulative downloaded volume from AUXIP by client per day in MB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "auxip_cumulative_downloaded_volume_by_client_per_day / 10000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative downloaded volume from AUXIP per month",
   "type": "timeseries",
   "description": "Cumulative downloaded volume from AUXIP per month in MB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "auxip_cumulative_downloaded_volume_per_month / 10000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative downloaded volume from AUXIP by client per month",
   "type": "timeseries",
   "description": "Cumulative downloaded volume from AUXIP by client per month in MB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "auxip_cumulative_downloaded_volume_by_client_per_month / 10000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative downloaded volume from AUXIP globally",
   "type": "timeseries",
   "description": "Cumulative downloaded volume from AUXIP globally in MB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "auxip_cumulative_downloaded_volume_globally / 10000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative downloaded volume from AUXIP by client globally",
   "type": "timeseries",
   "description": "Cumulative downloaded volume from AUXIP by client globally in MB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "auxip_cumulative_downloaded_volume_by_client_globally / 10000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}