global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    scrape_interval: 1m
      - targets: ["localhost:9090"]
  - job_name: "node_exporter"
    scrape_interval: 1m
    static_configs:
      - targets: ["adgs_node_exporter:9100"]
  - job_name: "cAdvisor"
    scrape_interval: 1m
    static_configs:
      - targets: ["adgs_cadvisor:8080"]
  - job_name: "adgsboa"
    scrape_interval: 1m
    static_configs:
      - targets: ["adgs_boa:5000"]