apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: https://adgs_prometheus:9090/adgs-metrics-manager
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      tlsSkipVerify: true
  - name: ADGS-BOA-DDBB
    type: grafana-postgresql-datasource
    access: proxy
    orgId: 1
    url: adgs_monitoring_db:5432
    basicAuth: true
    isDefault: false
    editable: true
    user: eboa
    database: eboadb
    postgresVersion: 1100
    readOnly: true
    jsonData:
      database: eboadb
      postgresVersion: 1100
      sslmode: disable